/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.0.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage for Queries:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * const result = await convex.query(myFunctionReference, { myArg: "foo" });
 * ```
 *
 * Usage for Mutations:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * const result = await convex.mutation(myFunctionReference, { myArg: "foo" });
 * ```
 *
 * Usage for Actions:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * const result = await convex.action(myFunctionReference, { myArg: "foo" });
 * ```
 */
declare const fullApi: ApiFromModules<{}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;